Revert to terraform init, then select
We tried putting `terraform workspace select` before `terraform init` to
avoid the error where the user already has a workspace selected, and that
workspace no longer exists. But, this doesn't work, and you get the
error:

```
Error: Initialization required. Please see the error message above.
```

So this change reverts back to running `terraform init` first, and then
running `terraform workspace select ...`