Add the jetstack helm repository, for cert-manager
We get cert-manager from the jetstack repository
now (see commit 6681b514633c91703cabb51031cd4679aa7cb88c)

This means we need the jetstack helm repository,
or we get failures like this during the components
install phase of creating a test cluster;

```

Error: Error applying plan:

1 error occurred:
        * helm_release.cert-manager: 1 error occurred:
        * helm_release.cert-manager: repo jetstack not found

```

This commit adds the helm repository, and uses it
when installing cert-manager.

Provider documentation is here:
https://www.terraform.io/docs/providers/helm/repository.html