upgrade audit (#1404)
* upgrade audit

getting lots of
```
marking and sending shard failed due to [failed to create shard]
java.io.IOException: failed to obtain in-memory shard lock
```
looks like we need more power