Add a dependency on prometheus to velero
If prometheus does not install correctly, we get the following
error when terraform tries to install velero:

    Error: rpc error: code = Unknown desc = validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
      on velero.tf line 82, in resource "helm_release" "velero":
      82: resource "helm_release" "velero" {

This change makes velero depend on prometheus, so that terraform
won't try to install velero until prometheus is installed.